# Generated by Django 5.0.6 on 2024-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_created_at_room_is_active_room_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory'), ('BOTH', 'Lecture & Category')], default='LECTURE', max_length=25),
        ),
    ]
