# Generated by Django 5.0.6 on 2024-10-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_room_category'),
        ('schedule', '0009_remove_courseschedule_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timeslots',
            field=models.ManyToManyField(blank=True, to='schedule.timeslot'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory')], default='LECTURE', max_length=25),
        ),
    ]
