# Generated by Django 5.0.6 on 2024-11-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_timeslots_alter_room_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='timeslots',
        ),
    ]
