# Generated by Django 5.0.6 on 2024-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_name'),
        ('room', '0005_remove_room_timeslots'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('number', 'floor', 'building'), name='unique_room_number_floor_per_building'),
        ),
    ]
