# Generated by Django 5.0.6 on 2024-11-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_unique_room_number_floor_per_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
    ]
