# Generated by Django 5.0.6 on 2024-11-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
