# Generated by Django 5.0.6 on 2024-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
