# Generated by Django 5.0.6 on 2024-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_building_available_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
