# Generated by Django 5.0.6 on 2024-11-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-created_at']},
        ),
    ]
