# Generated by Django 5.0.6 on 2024-11-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
