# Generated by Django 5.0.6 on 2024-10-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0009_remove_course_total_hours_remove_course_total_units_and_more'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.IntegerField(choices=[(1, 'FIRST YEAR'), (2, 'SECOND YEAR'), (3, 'THIRD YEAR'), (4, 'FOURTH YEAR')], default=1)),
                ('semester', models.CharField(choices=[('FIRST_SEMESTER', 'FIRST SEMESTER'), ('SECOND_SEMESTER', 'SECOND SEMESTER')], default='FIRST_SEMESTER', max_length=25)),
                ('courses', models.ManyToManyField(blank=True, to='course.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
            ],
            options={
                'db_table': 'curriculum',
            },
        ),
    ]
