# Generated by Django 5.0.6 on 2024-10-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('program', '0004_program_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.program'),
        ),
    ]
