//BSCS Curriculum

export const bscsFirstSemesterCourses = [
  {
    code: "MAT101",
    title: "Mathematics in the Modern World",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "PSY100",
    title: "Understanding the Self",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "READ100",
    title: "Science and Development of Reading",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "CCS101",
    title: "Introduction to Computing",
    lec: 2,
    lab: 1,
    total: 3,
    pre: "None",
  },
  {
    code: "CCS102",
    title: "Computer Programming 1",
    lec: 2,
    lab: 1,
    total: 3,
    pre: "None",
  },
  {
    code: "PHD101",
    title: "PnCians Holistic Development",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "NSTP1",
    title: "National Service Training Program 1",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "PED101",
    title: "Physical Activities Toward Health and Fitness 1",
    lec: 2,
    lab: 0,
    total: 2,
    pre: "None",
  },
  {
    code: "GAD",
    title: "Gender and Development",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
];

export const bscsSecondSemesterCourses = [
  {
    code: "HIS101",
    title: "Readings in Philippine History",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "HMN101",
    title: "Art Appreciation",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "CCS114",
    title: "Web Technologies",
    lec: 2,
    lab: 1,
    total: 3,
    pre: "None",
  },
  {
    code: "CCS103",
    title: "Computer Programming 2",
    lec: 2,
    lab: 1,
    total: 3,
    pre: "CCS102",
  },
  {
    code: "CCS105",
    title: "Human-Computer Interaction 1",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
  {
    code: "PHD102",
    title: "PnCians Holistic Development 2",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "PHD101",
  },
  {
    code: "NSTP2",
    title: "National Service Training Program 2",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "NSTP1",
  },
  {
    code: "PED102",
    title: "Physical Activities Toward Health and Fitness 2",
    lec: 2,
    lab: 0,
    total: 2,
    pre: "PED101",
  },
  {
    code: "COM101",
    title: "Purposive Communication",
    lec: 3,
    lab: 0,
    total: 3,
    pre: "None",
  },
];
