// // curriculumData.js


export const  data = [
  {
    acronym : "BSIT",
    firstYear : {
      firstSemester : {
        subject: [
          {
            code: "MAT101",
            title: "Mathematics in the Modern World",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
          { 
            code: "PSY100",
            title: "Understanding the Self",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
          {
            code: "READ100",
            title: "Science and Development of Reading",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
          {
            code: "CCS101",
            title: "Introduction to Computing",
            lec: 2,
            lab: 1,
            total: 3,
            pre: "None",
          },
          {
            code: "CCS102",
            title: "Computer Programming 1",
            lec: 2,
            lab: 1,
            total: 3,
            pre: "None",
          },
          {
            code: "PHD101",
            title: "PnCians Holistic Development",
            lec: 1,
            lab: 0,
            total: 1,
            pre: "None",
          },
          {
            code: "NSTP1",
            title: "National Service Training Program 1",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
          {
            code: "PED101",
            title: "Physical Activities Toward Health and Fitness 1",
            lec: 2,
            lab: 0,
            total: 2,
            pre: "None",
          },
          {
            code: "GAD101",
            title: "Gender and Development",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
        ],
      },
      secondSemester : {
        subject : [
          {
            code: "HIS101",
            title: "Readings in Philippine History",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
          {
            code: "HMN101",
            title: "Art Appreciation",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
          {
            code: "CCS114",
            title: "Web Technologies",
            lec: 2,
            lab: 1,
            total: 3,
            pre: "CCS101",
          },
          {
            code: "CCS103",
            title: "Computer Programming 2",
            lec: 2,
            lab: 1,
            total: 3,
            pre: "CCS102",
          },
          {
            code: "CCS105",
            title: "Human-Computer Interaction 1",
            lec: 2,
            lab: 1,
            total: 3,
            pre: "CCS101",
          },
          {
            code: "PHD102",
            title: "PnCians Holistic Development",
            lec: 1,
            lab: 0,
            total: 1,
            pre: "NSTP1",
          },
          {
            code: "NSTP2",
            title: "National Service Training Program 2",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "NSTP1",
          },
          {
            code: "PED102",
            title: "Physical Activities Toward Health and Fitness 2",
            lec: 2,
            lab: 0,
            total: 2,
            pre: "PED101",
          },
          {
            code: "COM101",
            title: "Purposive Communication",
            lec: 3,
            lab: 0,
            total: 3,
            pre: "None",
          },
        ]
      }
    },
    secondYear : {
      firstSemester : {
        subject : []
      },
      secondSemester : {
        subject : []
      }
    }
  },
  {
    acronym : "BSCS",
    firstSemester : {
      subject : [
        {
          code: "MAT101",
          title: "Mathematics in the Modern World",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PSY100",
          title: "Understanding the Self",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "READ100",
          title: "Science and Development of Reading",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "CCS101",
          title: "Introduction to Computing",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "None",
        },
        {
          code: "CCS102",
          title: "Computer Programming 1",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "None",
        },
        {
          code: "PHD101",
          title: "PnCians Holistic Development",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "NSTP1",
          title: "National Service Training Program 1",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PED101",
          title: "Physical Activities Toward Health and Fitness 1",
          lec: 2,
          lab: 0,
          total: 2,
          pre: "None",
        },
        {
          code: "GAD",
          title: "Gender and Development",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
      ],
    },
    secondSemester : {
      subject : [
        {
          code: "HIS101",
          title: "Readings in Philippine History",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "HMN101",
          title: "Art Appreciation",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "CCS114",
          title: "Web Technologies",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "None",
        },
        {
          code: "CCS103",
          title: "Computer Programming 2",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "CCS102",
        },
        {
          code: "CCS105",
          title: "Human-Computer Interaction 1",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PHD102",
          title: "PnCians Holistic Development 2",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "PHD101",
        },
        {
          code: "NSTP2",
          title: "National Service Training Program 2",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "NSTP1",
        },
        {
          code: "PED102",
          title: "Physical Activities Toward Health and Fitness 2",
          lec: 2,
          lab: 0,
          total: 2,
          pre: "PED101",
        },
        {
          code: "COM101",
          title: "Purposive Communication",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
      ]
    }
  },
  {
    acronym : "BSCE",
    firstSemester : {
      subject : [
        {
          code: "SDR1",
          title: "Science Development Reading",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "ITE101",
          title: "Living in the IT Era",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PHD101",
          title: "PnCians Holistic Development",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PSY100",
          title: "Understanding the Self",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "MAT101",
          title: "Mathematics in the Modern World",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "CPP101",
          title: "Computer Engineering as a Discipline",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "None",
        },
        {
          code: "CPP102",
          title: "Programming Logic and Design",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "None",
        },
        {
          code: "COE101",
          title: "Calculus 1",
          lec: 4,
          lab: 0,
          total: 4,
          pre: "None",
        },
        {
          code: "COE102",
          title: "Chemistry for Engineers",
          lec: 3,
          lab: 1,
          total: 4,
          pre: "None",
        },
        {
          code: "NSTP1",
          title: "National Service Training Program 1",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PED101",
          title: "Physical Education 1",
          lec: 2,
          lab: 0,
          total: 2,
          pre: "None",
        },
      ],
    },
    secondSemester : {
      subject : [
        {
          code: "GAD101",
          title: "Gender and Development",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "HIS101",
          title: "Readings in Philippine History",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "PHD102",
          title: "PnCians Holistic Development 2",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "PHD101",
        },
        {
          code: "COM101",
          title: "Purposive Communication",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "CPP103",
          title: "Object-Oriented Programming",
          lec: 2,
          lab: 1,
          total: 3,
          pre: "CPP102",
        },
        {
          code: "COE104",
          title: "Calculus 2",
          lec: 4,
          lab: 0,
          total: 4,
          pre: "COE101",
        },
        {
          code: "COE105",
          title: "Calculus-Based Physics",
          lec: 4,
          lab: 0,
          total: 4,
          pre: "COE101",
        },
        {
          code: "HMN101",
          title: "Art Appreciation",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "None",
        },
        {
          code: "NSTP2",
          title: "National Service Training Program 2",
          lec: 3,
          lab: 0,
          total: 3,
          pre: "NSTP1",
        },
        {
          code: "PED102",
          title: "Physical Education 2",
          lec: 2,
          lab: 0,
          total: 2,
          pre: "PED101",
        },
      ]
    }
  }
]
