# Generated by Django 5.0.6 on 2024-08-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5)),
                ('year_level', models.IntegerField()),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
            options={
                'db_table': 'section',
            },
        ),
    ]
