# Generated by Django 5.0.6 on 2024-09-02 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_alter_professor_handled_schedule'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.professor'),
        ),
    ]
