# Generated by Django 5.0.6 on 2024-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_alter_section_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
