# Generated by Django 5.0.6 on 2024-10-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_rename_department_id_program_department'),
        ('section', '0004_alter_section_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
