# Generated by Django 5.0.6 on 2024-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_section_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='year_level',
            field=models.IntegerField(choices=[(1, 'FIRST YEAR'), (2, 'SECOND YEAR'), (3, 'THIRD YEAR'), (4, 'FOURTH YEAR')], default=1),
        ),
    ]
