# Generated by Django 5.0.6 on 2024-10-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('program', '0004_program_acronym'),
        ('section', '0006_alter_section_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AlterField(
            model_name='section',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.program'),
        ),
    ]
