# Generated by Django 5.0.6 on 2024-10-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_section_department_alter_section_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='adviser',
        ),
    ]
