# Generated by Django 5.0.6 on 2024-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_acronym_alter_department_name'),
        ('program', '0005_alter_program_acronym_alter_program_name'),
        ('section', '0008_remove_section_adviser'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('label', 'year_level'), name='unique_section'),
        ),
    ]
