# Generated by Django 5.0.6 on 2024-09-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('professor', '0014_remove_professor_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.professor'),
        ),
    ]
