# Generated by Django 5.0.6 on 2024-09-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_options_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('R', 'Registrar'), ('DC', 'Department Chair'), ('D', 'Dean'), ('P', 'Professor'), ('VPAA', 'Vice President for Academic Affairs')], default='P', max_length=5),
        ),
    ]
