# Generated by Django 5.0.6 on 2024-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
