# Generated by Django 5.0.6 on 2024-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_authenticationhistory_delete_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
