# Generated by Django 5.0.6 on 2024-10-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_code'),
        ('department', '0001_initial'),
        ('program', '0004_program_acronym'),
        ('schedule', '0002_schedule_course_schedule_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.program'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('FIRST_SEMESTER', 'FIRST SEMESTER'), ('SECOND_SEMESTER', 'SECOND SEMESTER')], default='FIRST_SEMESTER', max_length=25),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year_level',
            field=models.IntegerField(choices=[(1, 'FIRST YEAR'), (2, 'SECOND YEAR'), (3, 'THIRD YEAR'), (4, 'FOURTH YEAR')], default=1),
        ),
    ]
