# Generated by Django 5.0.6 on 2024-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_day_of_week_remove_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='start_time',
            field=models.TimeField(default=0),
        ),
    ]
