# Generated by Django 5.0.6 on 2024-10-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_timeslot_delete_coursescheduletime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='timeslot',
        ),
    ]
