# Generated by Django 5.0.6 on 2024-10-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_courseschedule_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot'),
        ),
    ]
