# Generated by Django 5.0.6 on 2024-11-01 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_courseschedule_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='is_lab',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lab_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lab_timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_times', to='schedule.timeslot'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lecture_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lecture_timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_times', to='schedule.timeslot'),
        ),
    ]
