# Generated by Django 5.0.6 on 2024-11-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_remove_courseschedule_lab_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='lab_timeslot',
            field=models.ManyToManyField(blank=True, related_name='lab_times', to='schedule.timeslot'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='lecture_timeslot',
            field=models.ManyToManyField(blank=True, related_name='lecture_times', to='schedule.timeslot'),
        ),
    ]
