# Generated by Django 5.0.6 on 2024-11-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_remove_courseschedule_room_courseschedule_lab_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='course_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_timeslots', to='schedule.courseschedule'),
        ),
    ]
