# Generated by Django 5.0.6 on 2024-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_timeslots_alter_room_room_category'),
        ('schedule', '0015_timeslot_course_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='lab_room',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='lecture_room',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='course_schedule',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='room.room'),
        ),
    ]
