# Generated by Django 5.0.6 on 2024-11-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_timeslots_alter_room_room_category'),
        ('schedule', '0016_remove_courseschedule_lab_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='rooms',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lab_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_room_schedules', to='room.room'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lecture_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecture_room_schedules', to='room.room'),
        ),
    ]
