# Generated by Django 5.0.6 on 2024-11-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_remove_timeslot_rooms_courseschedule_lab_room_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeslot',
            table='timeslot',
        ),
    ]
