# Generated by Django 5.0.6 on 2024-11-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_alter_timeslot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='course_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.courseschedule'),
        ),
    ]
