# Generated by Django 5.0.6 on 2024-11-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_timeslot_course_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='course_schedule',
        ),
    ]
