# Generated by Django 5.0.6 on 2024-11-03 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_remove_timeslot_course_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='lab_timeslot',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='lecture_timeslot',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lab_time_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_time_schedule', to='schedule.timeslot'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='lecture_time_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecture_time_schedule', to='schedule.timeslot'),
        ),
    ]
