# Generated by Django 5.0.6 on 2024-11-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
    ]
