# Generated by Django 5.0.6 on 2024-10-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_units', models.IntegerField(default=18)),
                ('part_time_units', models.IntegerField(default=10)),
                ('full_time_units', models.IntegerField(default=21)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('vacant_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pairing_day', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'constraint',
            },
        ),
    ]
