# Generated by Django 5.0.6 on 2024-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constraint',
            options={'verbose_name': 'Constraint', 'verbose_name_plural': 'Constraints'},
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='casual_units',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='full_time_units',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='pairing_day',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='part_time_units',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='vacant_hours',
        ),
        migrations.AddField(
            model_name='constraint',
            name='classroom_capacity',
            field=models.BooleanField(default=True, help_text='Classroom capacity limit enforcement.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='daily_teaching_limit',
            field=models.BooleanField(default=True, help_text='Limit for daily teaching hours per professor.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='laboratory_sessions',
            field=models.BooleanField(default=True, help_text='Ensure lab sessions are in the same building or area as the next session.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='part_time_workload',
            field=models.PositiveIntegerField(default=0, help_text='Workload for part-time employment positions.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='permanent_workload',
            field=models.PositiveIntegerField(default=0, help_text='Workload for permanent employment positions.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='room_occupancy',
            field=models.BooleanField(default=True, help_text='Ensure rooms are not left empty for long periods.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='teaching_load',
            field=models.BooleanField(default=True, help_text='Professors should not teach two courses simultaneously.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='temporary_workload',
            field=models.PositiveIntegerField(default=0, help_text='Workload for temporary employment positions.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='transition_time',
            field=models.BooleanField(default=True, help_text='Minimum transition time between rooms.'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='wait_time',
            field=models.BooleanField(default=True, help_text='Maximum wait time between courses.'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='end_time',
            field=models.TimeField(default='18:00', help_text='Schedule end time.'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='start_time',
            field=models.TimeField(default='08:00', help_text='Schedule start time.'),
        ),
        migrations.AlterModelTable(
            name='constraint',
            table=None,
        ),
    ]
