# Generated by Django 5.0.6 on 2024-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0002_alter_constraint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='part_time_workload',
            field=models.PositiveIntegerField(default=12, help_text='Workload for part-time employment positions.'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='permanent_workload',
            field=models.PositiveIntegerField(default=21, help_text='Workload for permanent employment positions.'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='temporary_workload',
            field=models.PositiveIntegerField(default=24, help_text='Workload for temporary employment positions.'),
        ),
    ]
