# Generated by Django 5.0.6 on 2024-11-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0003_alter_constraint_part_time_workload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='teaching_load',
        ),
    ]
