# Generated by Django 5.0.6 on 2024-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0005_remove_constraint_classroom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='semester',
            field=models.CharField(choices=[('FIRST_SEMESTER', 'FIRST SEMESTER'), ('SECOND_SEMESTER', 'SECOND SEMESTER')], default='FIRST_SEMESTER', max_length=25),
        ),
    ]
