# Generated by Django 5.0.6 on 2024-11-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraint', '0006_constraint_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='room_occupancy',
        ),
        migrations.AlterField(
            model_name='constraint',
            name='daily_teaching_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=21600), help_text='Daily teaching limit (hours) for professors.'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='transition_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Transition time in minutes for sections.'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='wait_time',
            field=models.DurationField(default=datetime.timedelta(seconds=21600), help_text='Maximum wait time (hours) between courses.'),
        ),
    ]
