# Generated by Django 5.0.6 on 2024-09-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='program',
            table='program',
        ),
    ]
