# Generated by Django 5.0.6 on 2024-09-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='department_id',
            new_name='department',
        ),
    ]
