# Generated by Django 5.0.6 on 2024-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_rename_department_id_program_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
