# Generated by Django 5.0.6 on 2024-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_program_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
