# Generated by Django 5.0.6 on 2024-11-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_program_acronym_alter_program_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at']},
        ),
    ]
