# Generated by Django 5.0.6 on 2024-11-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_program_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
    ]
