# Generated by Django 5.0.6 on 2024-08-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('employment_status', models.CharField(choices=[('CASUAL', 'Casual'), ('PART_TIME', 'Part-time'), ('PERMANENT', 'Permanent')], max_length=25)),
                ('has_masteral', models.BooleanField(default=False)),
                ('required_units', models.IntegerField(default=0)),
                ('current_units', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('handled_schedule', models.ManyToManyField(to='schedule.schedule')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
    ]
