# Generated by Django 5.0.6 on 2024-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_professor_handled_schedule'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='handled_schedule',
            field=models.ManyToManyField(to='schedule.schedule'),
        ),
    ]
