# Generated by Django 5.0.6 on 2024-09-06 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_professor_account_alter_professor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
