# Generated by Django 5.0.6 on 2024-09-06 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0009_remove_professor_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
