# Generated by Django 5.0.6 on 2024-09-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0014_remove_professor_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='prof_id',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
