# Generated by Django 5.0.6 on 2024-09-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0015_professor_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_id',
            field=models.IntegerField(default=0),
        ),
    ]
