# Generated by Django 5.0.6 on 2024-09-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0016_alter_professor_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
