# Generated by Django 5.0.6 on 2024-09-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0021_alter_professor_current_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='has_masteral',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3),
        ),
    ]
