# Generated by Django 5.0.6 on 2024-09-10 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0023_alter_professor_has_masteral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
