# Generated by Django 5.0.6 on 2024-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0027_remove_professor_adivisee_professor_advisee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
