# Generated by Django 5.0.6 on 2024-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0028_alter_professor_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
