# Generated by Django 5.0.6 on 2024-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_current_hours_course_current_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory'), ('BOTH', 'Lecture & Category')], max_length=25),
        ),
    ]
