# Generated by Django 5.0.6 on 2024-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_department'),
        ('section', '0003_alter_section_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ManyToManyField(blank=True, to='section.section'),
        ),
    ]
