# Generated by Django 5.0.6 on 2024-10-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_rename_section_course_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='current_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='current_units',
        ),
    ]
